config/routes.rb
Links::Application.routes.draw do

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :links do
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy]

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :body, presence: true

  belongs_to :link
  belongs_to :user

end

app/models/link.rb
class Link < ActiveRecord::Base

  validates :url, :title, presence: true
  validates :url, :title, uniqueness: true


  belongs_to :user
  has_many :comments


end

app/models/user.rb
class User < ActiveRecord::Base

  validates :username, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :links

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    if user && user.is_password?(password)
      return user
    else
      return nil
    end
  end


  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def generate_session_token
    SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token
    self.session_token = generate_session_token
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  def sign_in(user)
    @current_user = user
    session[:session_token] = user.reset_session_token
  end

  def sign_out
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def signed_in?
    !!current_user
  end

  def require_sign_in
    redirect_to new_session_url if current_user.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    link = Link.find(params[:link_id])
    comment = link.comments.new(comment_params)
    comment.user_id = current_user.id

    comment.save
    flash[:errors] = comment.errors.full_messages
    redirect_to link_url(link)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to link_url(comment.link_id)
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  before_action :require_sign_in

  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id
    if @link.save
      redirect_to link_url(@link)
    else
      flash[:errors] = @link.errors.full_messages
      render :new
    end
  end

  def new
    @link = Link.new
    render :new
  end

  def show
    @link = Link.find(params[:id])
    render :show
  end

  def destroy
    link = Link.find(params[:id])
    link.destroy
    redirect_to links_url
  end

  def index
    @links = Link.all
    render :index
  end

  def update
    @link = Link.find(params[:id])
    if @link.update(link_params)
      redirect_to link_url(@link)
    else
      flash[:errors] = @link.errors.full_messages
      render :edit
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  private
  def link_params
    params.require(:link).permit(:title, :url)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_credentials(
            params[:user][:username],
            params[:user][:password])
    if @user
      sign_in(@user)
      redirect_to links_url(@user)
    else
      flash[:errors] = ["Incorrect username/password combo"]
      render :new
    end

  end

  def new
    @user = User.new
    render :new
  end

  def destroy
    sign_out
    render :new
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to links_url
    else
      flash[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
    render :new
  end


  private
  def user_params
    params.require(:user).permit(:username, :password)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Links</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if signed_in? %>
  <%= current_user.username %>

  <%= button_to "Sign Out", session_url, :method => :delete %>
<% else %>
  <%= link_to "Sign In", new_session_url %>
  <%= link_to "Sign Up", new_user_url %>
<% end %>
<br>
<%= yield %>

</body>
</html>

app/views/links/edit.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

<h2>Edit Link</h2>

<form action="<%= link_url(@link) %>" method="post">
  <input type="hidden" name="_method" value="put">

  <label>
    Title
    <input type="text" name="link[title]" value="<%= @link.title %>">
  </label>

  <label>
    URL
    <input type="text" name="link[url]" value="<%= @link.url %>">
  </label>

  <input type="submit" value="Update Link">
</form>

app/views/links/index.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

<% @links.each do |link| %>
<li><%= link_to link.title, link_url(link) %> : <%= link.url %></li>
  <%= "#{link.title}: " %>
  <%= link_to "Edit #{link.title}", edit_link_url(link)  %>
  <%= link_to "Delete #{link.title}", link_url(link), method: :delete %>
<br><br>
<% end %>

<%= link_to "New Link", new_link_url%>

app/views/links/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>

<h1>New Link</h1>

<form action="<%= links_url %>" method="post">

<label>
  Title:
<input type="text"
       name="link[title]"
       value="">
</label>
<br>
<label>
   URL:
  <input type="text"
         name="link[url]"
         value="">
</label>
<br>
<input type="submit" value="Create New Link">
</form>

app/views/links/show.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>


<%= link_to @link.url, @link.url %>
Title: <%= @link.title %> <br>

URL: <%= @link.url %> <br>
<h3>Comments</h3>

<% @link.comments.each do |comment| %>
  <%= comment.body %>
<% if comment.user_id == current_user.id %>
<%= button_to "Remove Comment", comment_url(comment), method: :delete %>
<% end %>
<br>
<% end %>

<h3>Add Comment</h3>
<form action="<%= link_comments_url(@link) %>" method="post">
  <label>Comment
  <input type="text"
         name="comment[body]"
         value="">
 </label>
  <input type="submit" value="Add Comment">

</form>

<br>
<%= link_to "Edit Link", edit_link_url(@link) %>
<%= link_to "Create New Link", new_link_url, method: :get%>
<%= link_to "All Links", links_url, method: :get%>

app/views/users/new.html.erb
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %><br>
  <% end %>
<% end %>
<h1>Sign Up</h1>
<form action="<%= users_url %>" method="post">
<label>
  Username:
  <input type="text"
         name="user[username]"
         value="">
</label>
<br>
<label>
  Password:
  <input type="password"
         name="user[password]"
         value="">
</label>
<br>
<button>Sign Up</button>
</form>
<br>
Already a user? <a href="<%= new_session_url %>">sign in</a>